# Generated by Django 5.1.7 on 2025-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_student_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="mother_occupation",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
