# Generated by Django 5.1.7 on 2025-07-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="7vyTpiUfe2DGAuJ127f5H0Rr5zs40Stz",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
