# Generated by Django 5.1.7 on 2025-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_auth", "0003_alter_passwordresetrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="token",
            field=models.CharField(
                default="aWrv5S2852wK3uneCKLOX9YhgILEYRkG",
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
    ]
